### DISCUSSION TITLE
"Token" as the fulcrum of standoff annotation and chunking in ATLAS

### DISCUSSION THREAD

**Discussion by jacobwegner** [scaife-viewer/scaife-viewer.org#7] [Ideas]
I hope to use this discussion to flesh out the importance of a `Token` in the ATLAS data model.

At a _very_ high level, token-level annotations are mapped to what is currently assumed to be white-space delimited tokens of a given text part ingested into ATLAS.

For example, given this urn:

```
urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.1
```

ATLAS is able to resolves the following tokens:

```
μῆνιν
ἄειδε
θεὰ
Πηληϊάδεω
Ἀχιλῆος
```

Internally, we assign a "virtual exemplar" to each token (the `veRef` value):

```yaml
---
tokens:
  edges:
  - node:
      veRef: 1.1.t1
      position: 1
      wordValue: μῆνιν
  - node:
      veRef: 1.1.t2
      position: 2
      wordValue: ἄειδε
  - node:
      veRef: 1.1.t3
      position: 3
      wordValue: θεὰ
  - node:
      veRef: 1.1.t4
      position: 4
      wordValue: Πηληϊάδεω
  - node:
      veRef: 1.1.t5
      position: 5
      wordValue: Ἀχιλῆος
```

**Comment by jacobwegner** [comment]
There are other approaches we've discussed for references and tokenization.

We could change to a whitespace-inclusive tokenization that changes when the unicode character category changes:

[urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.2](https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0012.tlg001.perseus-grc2:1.2)

```yaml
- position: 1
  value: οὐλομένην
  veRef: 1.2t1
  wordValue: οὐλομένην
- position: 2
  value: ','
  veRef: 1.2t2
  wordValue: ''
- position: 3
  value: ' '
  veRef: 1.2t3
  wordValue: ''
- position: 4
  value: ἣ
  veRef: 1.2t4
  wordValue: ἣ
- position: 5
  value: ' '
  veRef: 1.2t5
  wordValue: ''
- position: 6
  value: μυρίʼ
  veRef: 1.2t6
  wordValue: μυρίʼ
- position: 7
  value: ' '
  veRef: 1.2t7
  wordValue: ''
- position: 8
  value: Ἀχαιοῖς
  veRef: 1.2t8
  wordValue: Ἀχαιοῖς
- position: 9
  value: ' '
  veRef: 1.2t9
  wordValue: ''
- position: 10
  value: ἄλγεʼ
  veRef: 1.2t10
  wordValue: ἄλγεʼ
- position: 11
  value: ' '
  veRef: 1.2t11
  wordValue: ''
- position: 12
  value: ἔθηκε
  veRef: 1.2t12
  wordValue: ἔθηκε
- position: 13
  value: ','
  veRef: 1.2t13
  wordValue: ''
```
